### ISSUE TITLE
Can't open the admin page

### ISSUE THREAD

**Issue by JH-Chang** [ubccr/genesysv#3]
Hello!
I can't open the admin page (http://172.0.0.1/admin).

And when I use "python manage.py import_test_data"
Always will show the error message like below:
elasticsearch.exceptions.ConnectionError: ConnectionError((<urllib3.connection.HTTPConnection object at 0x7f3f793101d0>, 'Connection to 172.17.57.17 timed out. (connect timeout=10)')) caused by: ConnectTimeoutError((<urllib3.connection.HTTPConnection object at 0x7f3f793101d0>, 'Connection to 172.17.57.17 timed out. (connect timeout=10)'))

How can solve these problem ?

**Comment by mkzia** [comment]
1) The default access port is 8000. So try that. 

2) This means that you cannot connect to your Elasticsearch instance. Were you able to connect to Elasticsearch using your browser?

**Comment by JH-Chang** [comment]
Hello mkzia

1. I try "http://172.0.0.1:8000" . It doesn't work.
2. When I open "http://localhost:9200", I will see some information about elasticsearch.
    But it still show the error message like below:
    elasticsearch.exceptions.ConnectionError: ConnectionError((<urllib3.connection.HTTPConnection object at 0x7f3f793101d0>, 'Connection to 172.17.57.17 timed out. (connect timeout=10)')) caused by: ConnectTimeoutError((<urllib3.connection.HTTPConnection object at 0x7f3f793101d0>, 'Connection to 172.17.57.17 timed out. (connect timeout=10)'))
